# Site settings
title: Damjan Pavlica portfolio
description: Damjan Pavlica Web Developer portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Damjan Pavlica
user_title: Javascript Developer

exclude: ['package.json', 'src' , 'node_modules']
