# Site settings
title: Damjan Pavlica developer portfolio
description: Damjan Pavlica developer portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Damjan Pavlica
user_title: Software Developer
email: anon@anon.com
twitter_username: lorem_ipsum
github_username:  mudroljub
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
